@startuml
skinparam linetype ortho
hide empty members

class "recipes.example.com" as api <<api>>
class "/recipes" as index <<resouce>> {
    recipes
    --
    GET()
}
class "/recipes/new" as new <<resource>> {
    --
    POST(title, description, ingredients, instructions)
  }
class "/recipes/[ID]" as recipe <<resource>> {
    title
    description
    ingredients
    instructions
    --
    GET(id)
    PUT(title, description, ingredients, instructions)
    DELETE()
}

api --> index
api --> recipe
index --> recipe
index --> new

@enduml
